# Global build commands
[build]
  base = "studio/"
  command = "npm run build && cp netlify.toml dist && cp -r static dist"
  publish = "studio/dist/"
  functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"