# Global build commands
[build]
  base = "studio/"
  publish = "studio/dist/"
  functions = "functions/"
  command = "npm run build && cp netlify.toml dist && cp -r static dist"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"