# Global build commands
[build]
  base = "web/"
  command = "gatsby build"
  publish = "public/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Content-Security-Policy = "script-src 'unsafe-inline' 'unsafe-eval' http: https:"
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff;"
    X-XSS-Protection = "1; mode=block;"
    Access-Control-Allow-Origin = "*"

